### ISSUE TITLE
will run error in line 31

### ISSUE THREAD

**Issue by snakecy** [wnzhang/make-ipinyou-data#1]
if len(sys.argv) < 5:
    print 'Usage: ipinyou.folder 25 train.log.txt test.log.txt'
    # python splitadvertisers.py /home/weinan/Project/tqchen-exp/ipinyou/ 25 ../all/train.log.txt ../all/test.log.txt
    exit(-1)

" what's format in the file /home/weinan/Project/tqchen-exp/ipinyou/?
and 25 means generate files?

only 4 files after splitadvertisers.py?  why it still run?

**Comment by wnzhang** [comment]
In line 35 of Makefile, you will see what is really executed:
$(BASE)/python/splitadvertisers.py $(BASE) 25 $(BASE)/all/train.log.txt $(BASE)/all/test.log.txt

For your question about argv parameters count, please refer to:
http://stackoverflow.com/questions/2626026/python-sys-argv-lists-and-indexes
