### ISSUE TITLE
'device' not defined in latest pull

### ISSUE THREAD

**Issue by corallus** [wnzhang/make-ipinyou-data#6]
Was already warned in code inspection, because of this code in formalizeua.py:

```
    if ua.is_mobile:
        device = "m"
    elif ua.is_tablet:
        device = "t"
    elif ua.is_pc:
        device = "c"
```

Apparently there is a case in the train.log where none of these conditions are met.

Traceback (most recent call last):
  File "./python/formalizeua.py", line 41, in <module>
    output = output + '\t' + '\t'.join([device, device_family, os_family, browser])
NameError: name 'device' is not defined
make: *** [Makefile:28: train.log] Error 1

**Comment by liuxiaoxinhappy** [comment]
I have meet the same problem with you ,Have you resolved this question?

**Comment by wnzhang** [comment]
Sorry I didn't check a previous pull request carefully. Fixed.
