### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '1458/train.log.txt'

### ISSUE THREAD

**Issue by liuxiaoxinhappy** [wnzhang/make-ipinyou-data#8]
bash ./mkyzxdata.sh
1458
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '1458/train.log.txt'
2261
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '2261/train.log.txt'
2997
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '2997/train.log.txt'
3386
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '3386/train.log.txt'
3476
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '3476/train.log.txt'
2259
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '2259/train.log.txt'
2821
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '2821/train.log.txt'
3358
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '3358/train.log.txt'
3427
Traceback (most recent call last):
  File "python/mkyzx.py", line 54, in <module>
    fi = open(sys.argv[1], 'r')
IOError: [Errno 2] No such file or directory: '3427/train.log.txt'
make: *** [yzx] 错误 1
------------------------------------------------------------------------------------------
Hello Weinan Zhang,
I run "make all" for about seven hours and got the errors above,and under the folder "make-ipinyou-data" I got some folders named "227"、"238"、"241"、“249"、”254"、“277"、”294"、“300" rather than 1458  2261  2997  3386  3476 2259  2821  3358  3427.what should I do?
Thanks.

**Comment by Jacksonlark** [comment]
same problem+

**Comment by Jacksonlark** [comment]
Review the code, find the folders name created by script "python/splitadvertisers.py"

In this script, split index by given index id. Wrong results come from wrong index id(25 - bidprice). Right index is 28(advertiser).

**Comment by Lorne0** [comment]
Also found this problem.
However, after changing 25 to 28, the next line "bash ./mkyzxdata.sh" doesn't work. 
The error message looks like this:
3427
Traceback (most recent call last):
  File "python/mkyzx.py", line 78, in <module>
    col = namecol[f]
KeyError: 'useragent'

How can we fix it?
Futhermore, how do I make sure that the data after running the script is right? It seems that the data is somehow changed?

**Comment by Jacksonlark** [comment]
Read more, you can modify the field 'useragent'.

**Comment by wty9391** [comment]
There are two ways to fix this:
1)Just comment line 28 and line 32 of Makefile
2)In Makefile#L35 modify 25 to 28;
Remove filed 'useragent' in mkyzx.py#L14

**Comment by wty9391** [comment]
But formalizeua.py is very very very slow

**Comment by wnzhang** [comment]
We just merged a pull request to fix this problem. Thanks.
